import {
  MessageSquare,
  Mail,
  Webhook,
  Bot,
  CreditCard,
  Phone,
  Table2,
  Github,
  Cloud,
  Zap,
  Bell,
  Database,
  FileText,
  Send,
  Hash,
  Sparkles,
  Briefcase,
} from "lucide-react";
import type { IntegrationCategory, IntegrationType } from "./types";

export const integrationCategories: IntegrationCategory[] = [
  {
    id: "messaging",
    label: "Messaging",
    description: "Slack, Discord, Teams, and more",
  },
  {
    id: "email",
    label: "Email",
    description: "Transactional and marketing emails",
  },
  {
    id: "ai",
    label: "AI & LLM",
    description: "OpenAI, Claude, and AI services",
  },
  {
    id: "data",
    label: "Data & Storage",
    description: "Google Sheets, databases, and storage",
  },
  {
    id: "payments",
    label: "Payments",
    description: "Stripe, payment processing",
  },
  {
    id: "sms",
    label: "SMS & Voice",
    description: "Twilio, SMS notifications",
  },
  {
    id: "devtools",
    label: "Developer Tools",
    description: "GitHub, webhooks, and APIs",
  },
  {
    id: "crm",
    label: "CRM & Marketing",
    description: "HubSpot, CRM integrations",
  },
];

export const integrationTypes: IntegrationType[] = [
  // Messaging
  {
    id: "slack",
    label: "Slack",
    description: "Send messages to Slack channels and users",
    icon: Hash,
    color: "text-[#4A154B]",
    bgColor: "bg-[#4A154B]/10",
    category: "messaging",
    authType: "api_key",
    docsUrl: "https://api.slack.com/apps",
    features: ["Send messages", "Post to channels", "Rich formatting", "Block Kit support"],
    fields: [
      {
        key: "botToken",
        label: "Bot Token",
        type: "password",
        placeholder: "xoxb-your-bot-token-here",
        hint: "Must start with 'xoxb-'. Found in OAuth & Permissions > Bot User OAuth Token. NOT the Verification Token!",
        required: true,
      },
      {
        key: "defaultChannel",
        label: "Default Channel",
        type: "text",
        placeholder: "#general",
        hint: "Default channel for test messages (optional)",
        required: false,
      },
    ],
  },
  {
    id: "discord",
    label: "Discord",
    description: "Send messages via Discord webhooks",
    icon: MessageSquare,
    color: "text-[#5865F2]",
    bgColor: "bg-[#5865F2]/10",
    category: "messaging",
    authType: "webhook",
    docsUrl: "https://discord.com/developers/docs/resources/webhook",
    features: ["Webhook messages", "Embeds support", "Custom usernames", "File attachments"],
    fields: [
      {
        key: "webhookUrl",
        label: "Webhook URL",
        type: "url",
        placeholder: "https://discord.com/api/webhooks/...",
        hint: "Server Settings > Integrations > Webhooks",
        required: true,
      },
    ],
  },
  {
    id: "teams",
    label: "Microsoft Teams",
    description: "Send notifications to Teams channels",
    icon: MessageSquare,
    color: "text-[#6264A7]",
    bgColor: "bg-[#6264A7]/10",
    category: "messaging",
    authType: "webhook",
    docsUrl: "https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook",
    features: ["Channel messages", "Adaptive cards", "Rich formatting", "Action buttons"],
    fields: [
      {
        key: "webhookUrl",
        label: "Webhook URL",
        type: "url",
        placeholder: "https://outlook.office.com/webhook/...",
        hint: "Channel > Connectors > Incoming Webhook",
        required: true,
      },
    ],
  },

  // Email
  {
    id: "resend",
    label: "Resend",
    description: "Modern email API for developers",
    icon: Send,
    color: "text-black dark:text-white",
    bgColor: "bg-black/10 dark:bg-white/10",
    category: "email",
    authType: "api_key",
    docsUrl: "https://resend.com/docs",
    features: ["Transactional emails", "React Email support", "Analytics", "Webhooks"],
    fields: [
      {
        key: "apiKey",
        label: "API Key",
        type: "password",
        placeholder: "re_...",
        hint: "Found in Resend Dashboard > API Keys",
        required: true,
      },
      {
        key: "fromEmail",
        label: "From Email",
        type: "email",
        placeholder: "noreply@yourdomain.com",
        hint: "Must be a verified domain",
        required: true,
      },
    ],
  },
  {
    id: "sendgrid",
    label: "SendGrid",
    description: "Email delivery and marketing automation",
    icon: Mail,
    color: "text-[#1A82E2]",
    bgColor: "bg-[#1A82E2]/10",
    category: "email",
    authType: "api_key",
    docsUrl: "https://docs.sendgrid.com",
    features: ["Email API", "Templates", "Analytics", "Marketing campaigns"],
    fields: [
      {
        key: "apiKey",
        label: "API Key",
        type: "password",
        placeholder: "SG...",
        hint: "Settings > API Keys > Create API Key",
        required: true,
      },
      {
        key: "fromEmail",
        label: "From Email",
        type: "email",
        placeholder: "noreply@yourdomain.com",
        hint: "Must be a verified sender",
        required: true,
      },
    ],
  },
  {
    id: "smtp",
    label: "Custom SMTP",
    description: "Connect any SMTP email server",
    icon: Mail,
    color: "text-gray-600",
    bgColor: "bg-gray-600/10",
    category: "email",
    authType: "credentials",
    features: ["Any SMTP server", "Full control", "Self-hosted option"],
    fields: [
      {
        key: "host",
        label: "SMTP Host",
        type: "text",
        placeholder: "smtp.example.com",
        required: true,
      },
      {
        key: "port",
        label: "Port",
        type: "text",
        placeholder: "587",
        required: true,
      },
      {
        key: "username",
        label: "Username",
        type: "text",
        placeholder: "your-username",
        required: true,
      },
      {
        key: "password",
        label: "Password",
        type: "password",
        placeholder: "your-password",
        required: true,
      },
      {
        key: "fromEmail",
        label: "From Email",
        type: "email",
        placeholder: "noreply@yourdomain.com",
        required: true,
      },
      {
        key: "secure",
        label: "Security",
        type: "select",
        options: [
          { value: "tls", label: "TLS (Recommended)" },
          { value: "ssl", label: "SSL" },
          { value: "none", label: "None" },
        ],
      },
    ],
  },

  // AI & LLM
  {
    id: "openai",
    label: "OpenAI",
    description: "GPT-4, GPT-3.5, and embeddings",
    icon: Sparkles,
    color: "text-[#10A37F]",
    bgColor: "bg-[#10A37F]/10",
    category: "ai",
    authType: "api_key",
    docsUrl: "https://platform.openai.com/docs",
    features: ["Chat completions", "Embeddings", "Function calling", "Vision"],
    fields: [
      {
        key: "apiKey",
        label: "API Key",
        type: "password",
        placeholder: "sk-proj-... or sk-...",
        hint: "Must start with 'sk-'. Found at platform.openai.com > API Keys",
        required: true,
      },
      {
        key: "organization",
        label: "Organization ID",
        type: "text",
        placeholder: "org-... (optional)",
        hint: "For team/organization accounts",
        required: false,
      },
    ],
  },
  {
    id: "anthropic",
    label: "Anthropic Claude",
    description: "Claude 3.5 Sonnet, Opus, and Haiku",
    icon: Bot,
    color: "text-[#D4A27F]",
    bgColor: "bg-[#D4A27F]/10",
    category: "ai",
    authType: "api_key",
    docsUrl: "https://docs.anthropic.com",
    features: ["Long context", "Advanced reasoning", "Tool use", "Vision"],
    fields: [
      {
        key: "apiKey",
        label: "API Key",
        type: "password",
        placeholder: "sk-ant-api03-...",
        hint: "Must start with 'sk-ant-'. Found at console.anthropic.com > API Keys",
        required: true,
      },
    ],
  },

  // Data & Storage
  {
    id: "google-sheets",
    label: "Google Sheets",
    description: "Read and write spreadsheet data",
    icon: Table2,
    color: "text-[#34A853]",
    bgColor: "bg-[#34A853]/10",
    category: "data",
    authType: "oauth",
    docsUrl: "https://developers.google.com/sheets/api",
    features: ["Read rows", "Append data", "Update cells", "Create spreadsheets"],
    fields: [], // OAuth handled separately
  },
  {
    id: "google-drive",
    label: "Google Drive",
    description: "File storage and management",
    icon: Cloud,
    color: "text-[#4285F4]",
    bgColor: "bg-[#4285F4]/10",
    category: "data",
    authType: "oauth",
    docsUrl: "https://developers.google.com/drive/api",
    features: ["Upload files", "Share files", "Organize folders", "Search"],
    fields: [], // OAuth handled separately
  },
  {
    id: "dropbox",
    label: "Dropbox",
    description: "Cloud file storage",
    icon: Database,
    color: "text-[#0061FF]",
    bgColor: "bg-[#0061FF]/10",
    category: "data",
    authType: "oauth",
    docsUrl: "https://www.dropbox.com/developers",
    features: ["File upload", "File sharing", "Folder sync"],
    fields: [], // OAuth handled separately
  },

  // Payments
  {
    id: "stripe",
    label: "Stripe",
    description: "Payment processing and billing",
    icon: CreditCard,
    color: "text-[#635BFF]",
    bgColor: "bg-[#635BFF]/10",
    category: "payments",
    authType: "api_key",
    docsUrl: "https://stripe.com/docs",
    features: ["Payment intents", "Customers", "Subscriptions", "Checkout"],
    fields: [
      {
        key: "apiKey",
        label: "Secret Key",
        type: "password",
        placeholder: "sk_live_... or sk_test_...",
        hint: "Must start with 'sk_live_' or 'sk_test_'. NOT a Publishable Key (pk_)!",
        required: true,
      },
      {
        key: "webhookSecret",
        label: "Webhook Secret",
        type: "password",
        placeholder: "whsec_... (optional)",
        hint: "For webhook signature verification",
        required: false,
      },
    ],
  },

  // SMS & Voice
  {
    id: "twilio",
    label: "Twilio",
    description: "SMS, MMS, and voice calls",
    icon: Phone,
    color: "text-[#F22F46]",
    bgColor: "bg-[#F22F46]/10",
    category: "sms",
    authType: "credentials",
    docsUrl: "https://www.twilio.com/docs",
    features: ["SMS messaging", "MMS with media", "Phone lookup", "Voice calls"],
    fields: [
      {
        key: "accountSid",
        label: "Account SID",
        type: "text",
        placeholder: "ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        hint: "Must start with 'AC'. Found in Twilio Console Dashboard",
        required: true,
      },
      {
        key: "authToken",
        label: "Auth Token",
        type: "password",
        placeholder: "Your auth token",
        hint: "Found in Twilio Console Dashboard",
        required: true,
      },
      {
        key: "fromNumber",
        label: "From Number",
        type: "text",
        placeholder: "+1234567890",
        hint: "Your Twilio phone number (E.164 format)",
        required: true,
      },
    ],
  },

  // Developer Tools
  {
    id: "github",
    label: "GitHub",
    description: "Repository management and automation",
    icon: Github,
    color: "text-black dark:text-white",
    bgColor: "bg-black/10 dark:bg-white/10",
    category: "devtools",
    authType: "oauth",
    docsUrl: "https://docs.github.com",
    features: ["Issues", "Pull requests", "Repositories", "Actions"],
    fields: [], // OAuth handled separately
  },
  {
    id: "webhook",
    label: "Custom Webhook",
    description: "Send HTTP requests to any endpoint",
    icon: Webhook,
    color: "text-emerald-600",
    bgColor: "bg-emerald-600/10",
    category: "devtools",
    authType: "webhook",
    features: ["GET/POST/PUT/DELETE", "Custom headers", "JSON payload", "Retry logic"],
    fields: [
      {
        key: "url",
        label: "Webhook URL",
        type: "url",
        placeholder: "https://api.example.com/webhook",
        hint: "The endpoint to send requests to",
        required: true,
      },
      {
        key: "method",
        label: "Method",
        type: "select",
        options: [
          { value: "POST", label: "POST" },
          { value: "GET", label: "GET" },
          { value: "PUT", label: "PUT" },
          { value: "PATCH", label: "PATCH" },
          { value: "DELETE", label: "DELETE" },
        ],
      },
      {
        key: "headers",
        label: "Headers (JSON)",
        type: "textarea",
        placeholder: '{"Authorization": "Bearer ..."}',
        hint: "Optional custom headers as JSON",
        required: false,
      },
    ],
  },

  // CRM & Marketing
  {
    id: "hubspot",
    label: "HubSpot",
    description: "CRM and marketing automation",
    icon: Briefcase,
    color: "text-[#FF7A59]",
    bgColor: "bg-[#FF7A59]/10",
    category: "crm",
    authType: "oauth",
    docsUrl: "https://developers.hubspot.com",
    features: ["Contacts", "Deals", "Companies", "Email marketing"],
    fields: [], // OAuth handled separately
  },

  // Notifications
  {
    id: "push",
    label: "Push Notifications",
    description: "Browser and mobile push notifications",
    icon: Bell,
    color: "text-amber-600",
    bgColor: "bg-amber-600/10",
    category: "messaging",
    authType: "api_key",
    features: ["Browser push", "Mobile push", "Rich notifications"],
    fields: [
      {
        key: "vapidPublicKey",
        label: "VAPID Public Key",
        type: "text",
        placeholder: "Your VAPID public key",
        required: true,
      },
      {
        key: "vapidPrivateKey",
        label: "VAPID Private Key",
        type: "password",
        placeholder: "Your VAPID private key",
        required: true,
      },
    ],
  },
];

export const getIntegrationsByCategory = (categoryId: string): IntegrationType[] => {
  return integrationTypes.filter((t) => t.category === categoryId);
};

export const getIntegrationById = (id: string): IntegrationType | undefined => {
  return integrationTypes.find((t) => t.id === id);
};
